window.DESK_TIDY_VIDEO_LIBRARY = {
  schemaVersion: "1.0.0",
  manifestVersion: "1.0.0",
  verifiedDate: "2026-08-22",
  courseName: "Desk Tidy Guided Course",
  title: "Desk Tidy video learning",
  introduction: "Short, section-linked clips that help you notice one useful idea before returning to the Desk Tidy theory and evidence task. The approved drawing, teacher demonstration and current school safety directions always control practical work.",
  backHref: "../index.html",
  mainMenuHref: "https://stevencowell.github.io/Main-Page/",
  sections: [
    {
      order: 1,
      moduleId: "M01",
      moduleLabel: "Weeks 1–2",
      moduleTitle: "Brief, safety and materials",
      sectionId: "design-brief",
      sectionTitle: "Designing for an organised workspace",
      theoryPath: "weeks1-2/index.html#design-brief",
      outcome: "MATCHED",
      teachingClaim: "A useful design brief identifies a real user, their need and a testable goal without prescribing one finished solution.",
      reasonToWatch: "See how a user need can guide ideas and later become a measure of success.",
      watchFor: "Which three parts turn a broad problem into a usable user-need statement?",
      equivalentPath: "Read the adjacent explanation about the intended user, storage need and measurable design criteria, then answer the design-brief knowledge checks. No video is needed to complete them.",
      evidenceLink: "Supports the design-brief checks and the student explanation of user, need and measurable criteria.",
      sourceBoundary: "The clip explains a general design-thinking pattern. The Desk Tidy brief and criteria on the course page control this project.",
      video: {
        id: "kT0ZqwdPYRM",
        title: "User Need Statements in Design Thinking",
        channel: "NNgroup",
        durationSeconds: 187,
        durationLabel: "3:07",
        segmentStart: 31,
        segmentEnd: 106,
        segmentLabel: "0:31–1:46",
        sampledSegment: "0:31–1:06",
        sampleEvidence: "Defines a user-need statement as the user, need and goal, then links it to a metric for success.",
        intelligibility: "PASS — clear paced narration with manual English captions; sampled wording is suitable for secondary students.",
        thumbnailUrl: "https://i.ytimg.com/vi/kT0ZqwdPYRM/maxresdefault.jpg",
        thumbnailWidth: 1280,
        thumbnailHeight: 720,
        watchUrl: "https://www.youtube.com/watch?v=kT0ZqwdPYRM&t=31s",
        embedUrl: "https://www.youtube-nocookie.com/embed/kT0ZqwdPYRM"
      }
    },
    {
      order: 2,
      moduleId: "M01",
      moduleLabel: "Weeks 1–2",
      moduleTitle: "Brief, safety and materials",
      sectionId: "workshop-safety",
      sectionTitle: "Hazards, risks and controls in the timber workshop",
      theoryPath: "weeks1-2/index.html#workshop-safety",
      outcome: "MATCHED",
      teachingClaim: "Risk controls are considered from strongest to weakest, with PPE as the final layer rather than the first or only response.",
      reasonToWatch: "See why controls closer to the hazard are usually more reliable than relying only on individual behaviour.",
      watchFor: "What makes elimination, substitution and engineering controls stronger than PPE alone?",
      equivalentPath: "Use the hierarchy diagram and hazard-control explanation in the adjacent theory, then complete the workshop-safety checks. Current teacher directions remain the authority.",
      evidenceLink: "Supports the risk-control decision checks and the explanation of why PPE is the final layer.",
      sourceBoundary: "The clip teaches the hierarchy concept only. It does not authorise a tool, PPE item, local control or practical activity.",
      inheritedUse: "RETAINED",
      video: {
        id: "XOkPcLD5Soo",
        title: "The Hierarchy of Controls",
        channel: "Healthier Workforce Center",
        durationSeconds: 313,
        durationLabel: "5:13",
        segmentStart: 44,
        segmentEnd: 190,
        segmentLabel: "0:44–3:10",
        sampledSegment: "0:44–1:15",
        sampleEvidence: "Names the hierarchy from elimination to PPE and explains that stronger controls do not depend only on individual behaviour.",
        intelligibility: "PASS — coherent spoken explanation and usable auto-generated English captions in the sampled segment.",
        thumbnailUrl: "https://i.ytimg.com/vi/XOkPcLD5Soo/maxresdefault.jpg",
        thumbnailWidth: 1280,
        thumbnailHeight: 720,
        watchUrl: "https://www.youtube.com/watch?v=XOkPcLD5Soo&t=44s",
        embedUrl: "https://www.youtube-nocookie.com/embed/XOkPcLD5Soo"
      }
    },
    {
      order: 3,
      moduleId: "M01",
      moduleLabel: "Weeks 1–2",
      moduleTitle: "Brief, safety and materials",
      sectionId: "materials",
      sectionTitle: "Choosing materials responsibly",
      theoryPath: "weeks1-2/index.html#materials",
      outcome: "MATCHED",
      teachingClaim: "Material choice should follow observed properties and intended use; natural timber has grain direction and related working behaviour.",
      reasonToWatch: "Notice the three solid-timber behaviours a designer considers before choosing or cutting stock.",
      watchFor: "Which three properties does the presenter check before making the first cut?",
      equivalentPath: "Use the radiata pine and MDF comparison image and adjacent material-properties explanation, then complete the material-choice checks. That path also covers responsible stock use and durability.",
      evidenceLink: "Supports comparison of observed material properties before a justified selection.",
      sourceBoundary: "The selected segment concerns solid-timber grain, movement and strength. The adjacent Desk Tidy theory controls the pine/MDF comparison and sustainability discussion.",
      inheritedUse: "RETAINED_WITH_FOCUSED_SEGMENT",
      longClipReason: "The inherited 11:19 clip is retained because its opening one-minute explanation is a strong, clear account of the exact timber behaviour claim. Playback is focused to 0:27–1:27; students do not need the full clip.",
      video: {
        id: "oZkYLVrTYe4",
        title: "The Way Wood Works -- What Every Woodworker Needs to Know About Wood.",
        channel: "Workshop Companion",
        durationSeconds: 679,
        durationLabel: "11:19",
        segmentStart: 27,
        segmentEnd: 87,
        segmentLabel: "0:27–1:27",
        sampledSegment: "0:27–1:27",
        sampleEvidence: "Explains that wood has grain, moves more across the grain and is stronger along the grain, then introduces fibre direction.",
        intelligibility: "PASS — clear measured narration with coherent auto-generated English captions in the focused segment.",
        thumbnailUrl: "https://i.ytimg.com/vi/oZkYLVrTYe4/maxresdefault.jpg",
        thumbnailWidth: 1280,
        thumbnailHeight: 720,
        watchUrl: "https://www.youtube.com/watch?v=oZkYLVrTYe4&t=27s",
        embedUrl: "https://www.youtube-nocookie.com/embed/oZkYLVrTYe4"
      }
    },
    {
      order: 4,
      moduleId: "M02",
      moduleLabel: "Weeks 3–4",
      moduleTitle: "Research and develop ideas",
      sectionId: "research-concepts",
      sectionTitle: "Researching organisers and generating four concepts",
      theoryPath: "weeks3-4/index.html#research-concepts",
      outcome: "MATCHED",
      teachingClaim: "Concepts become comparable when sketches clearly communicate different arrangements and are supported by purposeful annotations.",
      reasonToWatch: "See a student-friendly way to give several concept sketches enough space for clear visual communication and annotation.",
      watchFor: "What layout choices keep separate ideas and their annotations easy to compare?",
      equivalentPath: "Read the adjacent explanation about researching organisers, producing four genuinely different concepts and annotating decisions, then complete the concept-development checks.",
      evidenceLink: "Supports the four-concept folio evidence and annotations linked to user needs and criteria.",
      sourceBoundary: "The presenter uses six designs as an example. Desk Tidy students produce the four genuinely different concepts required by the course page.",
      video: {
        id: "5wCH3nBUPU4",
        title: "Initial ideas sketches | Design and technology | GCSE NEA",
        channel: "Mr Leisk D&T",
        durationSeconds: 155,
        durationLabel: "2:35",
        segmentStart: 0,
        segmentEnd: 119,
        segmentLabel: "0:00–1:59",
        sampledSegment: "0:00–1:29",
        sampleEvidence: "Shows a layout for younger students, links supporting sketches, checks line quality and leaves space for annotations.",
        intelligibility: "PASS — accessible instructional narration with coherent auto-generated English captions in the sampled segment.",
        thumbnailUrl: "https://i.ytimg.com/vi/5wCH3nBUPU4/maxresdefault.jpg",
        thumbnailWidth: 1280,
        thumbnailHeight: 720,
        watchUrl: "https://www.youtube.com/watch?v=5wCH3nBUPU4",
        embedUrl: "https://www.youtube-nocookie.com/embed/5wCH3nBUPU4"
      }
    },
    {
      order: 5,
      moduleId: "M02",
      moduleLabel: "Weeks 3–4",
      moduleTitle: "Research and develop ideas",
      sectionId: "compare-concepts",
      sectionTitle: "Comparing concepts and justifying a preferred design",
      theoryPath: "weeks3-4/index.html#compare-concepts",
      outcome: "MATCHED",
      teachingClaim: "A decision matrix compares every option against the same criteria and supports, rather than replaces, reasoned judgement.",
      reasonToWatch: "Follow the order used to compare options, weight criteria and sense-check the result.",
      watchFor: "Why should the final matrix total still be checked against the quality of the evidence and weightings?",
      equivalentPath: "Use the decision-matrix example in the adjacent theory, score each concept against the same criteria and record the evidence behind each score.",
      evidenceLink: "Supports the concept-comparison checks and the justification of the preferred design.",
      sourceBoundary: "The supplier example demonstrates the method only. Desk Tidy criteria and concept evidence control the student's decision.",
      inheritedUse: "RETAINED",
      video: {
        id: "xO7xJ1sTyPI",
        title: "Decision Matrix Analysis: How to Make a Good Decision by Weighing Up Different Factors",
        channel: "Mindtools Kineo",
        durationSeconds: 124,
        durationLabel: "2:04",
        segmentStart: 7,
        segmentEnd: 115,
        segmentLabel: "0:07–1:55",
        sampledSegment: "0:07–1:19",
        sampleEvidence: "Explains options as rows, factors as columns, relative importance and evidence-based scoring before a sense-check.",
        intelligibility: "PASS — clear professional narration with manual English captions.",
        thumbnailUrl: "https://i.ytimg.com/vi/xO7xJ1sTyPI/maxresdefault.jpg",
        thumbnailWidth: 1280,
        thumbnailHeight: 720,
        watchUrl: "https://www.youtube.com/watch?v=xO7xJ1sTyPI&t=7s",
        embedUrl: "https://www.youtube-nocookie.com/embed/xO7xJ1sTyPI"
      }
    },
    {
      order: 6,
      moduleId: "M02",
      moduleLabel: "Weeks 3–4",
      moduleTitle: "Research and develop ideas",
      sectionId: "respectful-design",
      sectionTitle: "Learning respectfully from Aboriginal and Torres Strait Islander design knowledge",
      theoryPath: "weeks3-4/index.html#respectful-design",
      outcome: "MATCHED",
      teachingClaim: "First Nations cultural knowledge and expressions carry rights, context and authority; public visibility is not permission to copy.",
      reasonToWatch: "Hear a First Nations-led explanation of why Indigenous Cultural and Intellectual Property protection matters.",
      watchFor: "Why does the speaker say the development of stronger protections must be First Nations-led?",
      equivalentPath: "Read the adjacent respectful-design explanation, follow its stop-and-check pathway for uncertain authority or permission, and complete the source/context/reflection evidence.",
      evidenceLink: "Supports the respectful-research checks and the folio record of source, context, permission and design decision.",
      sourceBoundary: "The clip explains the policy problem and consultation. It does not grant permission to reuse any cultural element. The Office for the Arts still describes legislative options as under development at the 2026-08-22 check.",
      inheritedUse: "RETAINED_AFTER_CURRENCY_CHECK",
      video: {
        id: "W6zGG6tYGr0",
        title: "Protecting Indigenous Cultural and Intellectual Property rights (ICIP)",
        channel: "Infra, Transport, Regional, Comms, Sport & Arts",
        durationSeconds: 123,
        durationLabel: "2:03",
        segmentStart: 0,
        segmentEnd: 105,
        segmentLabel: "0:00–1:45",
        sampledSegment: "0:00–1:34",
        sampleEvidence: "A Wuthathi and Mabuiag Islander policy lead explains fake art harms, First Nations-led consultation and proposed protections.",
        intelligibility: "PASS — clear professional narration with manual English captions.",
        thumbnailUrl: "https://i.ytimg.com/vi/W6zGG6tYGr0/maxresdefault.jpg",
        thumbnailWidth: 1280,
        thumbnailHeight: 720,
        watchUrl: "https://www.youtube.com/watch?v=W6zGG6tYGr0",
        embedUrl: "https://www.youtube-nocookie.com/embed/W6zGG6tYGr0"
      }
    },
    {
      order: 7,
      moduleId: "M03",
      moduleLabel: "Weeks 5–6",
      moduleTitle: "Draw and plan production",
      sectionId: "working-drawings",
      sectionTitle: "Communicating the selected design with working drawings",
      theoryPath: "weeks5-6/index.html#working-drawings",
      outcome: "MATCHED",
      teachingClaim: "Related orthographic views communicate different faces of the same approved form and must align consistently.",
      reasonToWatch: "Watch a simple 3D form become related front, right-side and top views.",
      watchFor: "Which dimensions stay aligned as the presenter projects one view from another?",
      equivalentPath: "Use the orthographic-view diagram and working-drawing explanation beside this section, then check view alignment and written dimensions in the approved drawing set.",
      evidenceLink: "Supports the working-drawing checks about view relationships, dimensions and production readiness.",
      sourceBoundary: "The demonstration object and centimetre example are not Desk Tidy production information. Only the approved Desk Tidy drawing and written millimetre dimensions may control manufacture.",
      inheritedUse: "RETAINED_ONLY_FOR_THIS_MATCHING_SECTION",
      video: {
        id: "BiwmJ4t2KWM",
        title: "Introduction to orthographic drawing",
        channel: "Riaan Meeser",
        durationSeconds: 306,
        durationLabel: "5:06",
        segmentStart: 1,
        segmentEnd: 305,
        segmentLabel: "0:01–5:05",
        sampledSegment: "0:01–1:36",
        sampleEvidence: "Distinguishes one isometric view from multiple 2D orthographic views and establishes the main, right-side and top-view relationship.",
        intelligibility: "PASS — steady explanation with coherent auto-generated English captions; mathematical language is readable for the cohort.",
        thumbnailUrl: "https://i.ytimg.com/vi/BiwmJ4t2KWM/mqdefault.jpg",
        thumbnailWidth: 320,
        thumbnailHeight: 180,
        watchUrl: "https://www.youtube.com/watch?v=BiwmJ4t2KWM",
        embedUrl: "https://www.youtube-nocookie.com/embed/BiwmJ4t2KWM"
      }
    },
    {
      order: 8,
      moduleId: "M03",
      moduleLabel: "Weeks 5–6",
      moduleTitle: "Draw and plan production",
      sectionId: "cutting-schedule",
      sectionTitle: "Cutting lists and a realistic production schedule",
      theoryPath: "weeks5-6/index.html#cutting-schedule",
      outcome: "MATCHED",
      teachingClaim: "A realistic production schedule puts tasks in order, estimates time and makes dependencies and quality gates visible.",
      reasonToWatch: "See how short production tasks and their planned lesson time are recorded on a simple Gantt chart.",
      watchFor: "How does the chart show both task order and the time allowed for each task?",
      equivalentPath: "Read the adjacent cutting-list and production-schedule explanation, then cross-check parts, quantities, approved dimensions, task order, milestones and contingency time.",
      evidenceLink: "Supports the planning checks and the student's cutting-list and production-schedule evidence.",
      sourceBoundary: "The GCSE table example and its furniture tasks are illustrative only. Desk Tidy parts, dimensions, processes and timings must come from the approved drawing and teacher direction.",
      video: {
        id: "6y5xhXGr7TM",
        title: "GCSE D&T NEA walkthrough development Gantt Chart",
        channel: "MR Ridley Design & Technology",
        durationSeconds: 176,
        durationLabel: "2:56",
        segmentStart: 26,
        segmentEnd: 146,
        segmentLabel: "0:26–2:26",
        sampledSegment: "0:26–1:56",
        sampleEvidence: "Shows tasks listed against hours and explains that one task may span several hours while several short tasks may share one hour.",
        intelligibility: "PASS — conversational classroom narration with coherent auto-generated English captions in the sampled segment.",
        thumbnailUrl: "https://i.ytimg.com/vi/6y5xhXGr7TM/mqdefault.jpg",
        thumbnailWidth: 320,
        thumbnailHeight: 180,
        watchUrl: "https://www.youtube.com/watch?v=6y5xhXGr7TM&t=26s",
        embedUrl: "https://www.youtube-nocookie.com/embed/6y5xhXGr7TM"
      }
    },
    {
      order: 9,
      moduleId: "M03",
      moduleLabel: "Weeks 5–6",
      moduleTitle: "Draw and plan production",
      sectionId: "accurate-markout",
      sectionTitle: "Datums and accurate marking out",
      theoryPath: "weeks5-6/index.html#accurate-markout",
      outcome: "MATCHED",
      teachingClaim: "Selecting consistent reference faces and edges prevents related measurements and square lines from accumulating error.",
      reasonToWatch: "See why the stock of a square or gauge stays against the selected reference face or edge.",
      watchFor: "What happens to lines around a component when the reference face and edge are not used consistently?",
      equivalentPath: "Use the datum diagram and marking-out explanation beside the section, then complete the checks about parallax, square lines, waste-side marks and teacher approval before cutting.",
      evidenceLink: "Supports the datum and accurate-marking checks before irreversible production work.",
      sourceBoundary: "The clip explains reference-face practice. The approved drawing, demonstrated school tools and teacher check control the student's actual mark-out.",
      inheritedUse: "RETAINED_ONLY_FOR_THIS_MATCHING_SECTION",
      video: {
        id: "SNaSW5b9aWE",
        title: "Face edge and face side",
        channel: "Mike Worth",
        durationSeconds: 252,
        durationLabel: "4:12",
        segmentStart: 5,
        segmentEnd: 211,
        segmentLabel: "0:05–3:31",
        sampledSegment: "0:36–1:07",
        sampleEvidence: "Explains that the square or gauge stock stays on a selected reference surface and that inconsistent references make lines fail to meet.",
        intelligibility: "PASS — clear measured narration with manual English captions.",
        thumbnailUrl: "https://i.ytimg.com/vi/SNaSW5b9aWE/maxresdefault.jpg",
        thumbnailWidth: 1280,
        thumbnailHeight: 720,
        watchUrl: "https://www.youtube.com/watch?v=SNaSW5b9aWE&t=5s",
        embedUrl: "https://www.youtube-nocookie.com/embed/SNaSW5b9aWE"
      }
    },
    {
      order: 10,
      moduleId: "M04",
      moduleLabel: "Weeks 7–8",
      moduleTitle: "Make and assemble",
      sectionId: "cutting-shaping",
      sectionTitle: "Cutting and shaping components accurately",
      theoryPath: "weeks7-8/index.html#cutting-shaping",
      outcome: "MATCHED",
      teachingClaim: "Accurate hand-sawing depends on stable support, a clear waste-side mark and controlled tracking before refinement to final size.",
      reasonToWatch: "Observe how the work is supported and how the presenter keeps the saw tracking on the intended side of the line.",
      watchFor: "Which setup details help the cut stay square and preserve the required material?",
      equivalentPath: "Read the adjacent cutting-and-shaping explanation and use its waste-side, secure-work, stop-and-check and teacher-approval sequence. Do not copy an online method without the teacher demonstration.",
      evidenceLink: "Supports checks about the waste side, stable workholding, controlled refinement and stopping when a cut wanders.",
      sourceBoundary: "Watch for principles only. The clip's knife-line and chisel-groove method is not an instruction to students; actual tools and processes require the current teacher demonstration and authorisation.",
      video: {
        id: "pGmNeseMuQM",
        title: "Top Tips - Sawing accurately with a bench hook",
        channel: "Axminster Tools",
        durationSeconds: 77,
        durationLabel: "1:17",
        segmentStart: 0,
        segmentEnd: 74,
        segmentLabel: "0:00–1:14",
        sampledSegment: "0:00–1:14",
        sampleEvidence: "Shows a waste mark, supported timber, a bench hook and controlled saw tracking to preserve a square result.",
        intelligibility: "PASS — short, clear instructional narration with coherent auto-generated English captions.",
        thumbnailUrl: "https://i.ytimg.com/vi/pGmNeseMuQM/maxresdefault.jpg",
        thumbnailWidth: 1280,
        thumbnailHeight: 720,
        watchUrl: "https://www.youtube.com/watch?v=pGmNeseMuQM",
        embedUrl: "https://www.youtube-nocookie.com/embed/pGmNeseMuQM"
      }
    },
    {
      order: 11,
      moduleId: "M04",
      moduleLabel: "Weeks 7–8",
      moduleTitle: "Make and assemble",
      sectionId: "joint-choices",
      sectionTitle: "Butt, rebate and dowel joints in a Desk Tidy",
      theoryPath: "weeks7-8/index.html#joint-choices",
      outcome: "MATCHED",
      teachingClaim: "Joint suitability depends on how surfaces locate, align and provide glue area; strength alone does not select the project joint.",
      reasonToWatch: "Compare a simple butt relationship with locating rebates and dowels, then return to the project-specific choice.",
      watchFor: "How do locating features and extra glue surface change alignment and joint behaviour?",
      equivalentPath: "Use the butt, rebate and dowel comparison image and adjacent explanation, then justify the teacher-approved joint against the actual component relationship.",
      evidenceLink: "Supports the joint-comparison checks and a reasoned, source-safe joint choice.",
      sourceBoundary: "The clip surveys several joints and uses the US term “rabbet” for a rebate. It does not approve a Desk Tidy joint or practical method.",
      inheritedUse: "RETAINED_ONLY_FOR_THIS_MATCHING_SECTION",
      video: {
        id: "gyXL9YCg-rU",
        title: "Understanding Wood Joints | Ask This Old House",
        channel: "This Old House",
        durationSeconds: 373,
        durationLabel: "6:13",
        segmentStart: 0,
        segmentEnd: 146,
        segmentLabel: "0:00–2:26",
        sampledSegment: "0:00–2:26",
        sampleEvidence: "Compares butt and locating joints, explains glue surface and shows that dowel positions must align consistently.",
        intelligibility: "PASS — clear conversational spoken English with coherent auto-generated captions in the focused segment.",
        thumbnailUrl: "https://i.ytimg.com/vi/gyXL9YCg-rU/maxresdefault.jpg",
        thumbnailWidth: 1280,
        thumbnailHeight: 720,
        watchUrl: "https://www.youtube.com/watch?v=gyXL9YCg-rU",
        embedUrl: "https://www.youtube-nocookie.com/embed/gyXL9YCg-rU"
      }
    },
    {
      order: 12,
      moduleId: "M04",
      moduleLabel: "Weeks 7–8",
      moduleTitle: "Make and assemble",
      sectionId: "dry-fit-glue",
      sectionTitle: "Dry fitting, PVA assembly and surface preparation",
      theoryPath: "weeks7-8/index.html#dry-fit-glue",
      outcome: "MATCHED",
      teachingClaim: "Clamps hold accurately fitted surfaces while adhesive sets; excessive pressure is not a repair for poor fit.",
      reasonToWatch: "See why a light-tight dry fit matters before adhesive and clamps make correction harder.",
      watchFor: "Why can extra clamp pressure make a poor-fitting joint worse rather than fix it?",
      equivalentPath: "Follow the adjacent dry-fit sequence: check fit, order, squareness and clamp access; diagnose gaps; use PVA and surface preparation only as demonstrated by the teacher.",
      evidenceLink: "Supports the dry-fit and clamping checks, including why glue cannot fill an inaccurate joint.",
      sourceBoundary: "The clip explains clamping pressure only. The local PVA product, amount, open time, cleanup, clamp arrangement and curing instructions remain teacher-controlled.",
      video: {
        id: "5cy1wmzGC28",
        title: "Gluing Tips - Clamping Pressure",
        channel: "Titebond",
        durationSeconds: 65,
        durationLabel: "1:05",
        segmentStart: 3,
        segmentEnd: 65,
        segmentLabel: "0:03–1:05",
        sampledSegment: "0:03–1:05",
        sampleEvidence: "Explains that clamps hold mated edges while glue sets and that forcing poorly fitted edges creates uneven pressure and stored stress.",
        intelligibility: "PASS — concise manufacturer narration with coherent auto-generated English captions.",
        thumbnailUrl: "https://i.ytimg.com/vi/5cy1wmzGC28/maxresdefault.jpg",
        thumbnailWidth: 1280,
        thumbnailHeight: 720,
        watchUrl: "https://www.youtube.com/watch?v=5cy1wmzGC28&t=3s",
        embedUrl: "https://www.youtube-nocookie.com/embed/5cy1wmzGC28"
      }
    },
    {
      order: 13,
      moduleId: "M05",
      moduleLabel: "Weeks 9–10",
      moduleTitle: "Finish, test and reflect",
      sectionId: "clear-finish",
      sectionTitle: "Applying a clear finish safely and evenly",
      theoryPath: "weeks9-10/index.html#clear-finish",
      outcome: "GAP",
      teachingClaim: "The authorised unit uses one coat of water-based clear varnish, applied only after the teacher demonstration and according to current product information.",
      reasonToWatch: "No responsible clip is assigned because generic finishing directions would compete with the current local product and teacher-controlled process.",
      watchFor: "No video required. Use the finish-quality checklist in the theory section.",
      equivalentPath: "Read the complete adjacent finish explanation and checklist, inspect the surface under good light, and follow only the current teacher demonstration and product information.",
      evidenceLink: "Supports the finish-readiness checks and the student's evidence photographs without inventing a product method.",
      sourceBoundary: "This gap is deliberate. The project unit specifies one coat of water-based clear varnish but does not supply the current product, SDS or approved application method.",
      gapReason: "Checked clips either discuss broad finish selection or prescribe multiple coats, sanding between coats, steel wool, product-specific drying times or other directions that conflict with the authorised one-coat, teacher/product-information boundary. A generic clip would be misleading.",
      rejectedCandidateIds: ["bbiXJd_1l8Y", "77nsY4EbVpg", "t3gdJqiFHnM", "dCYMxs45g6o"]
    },
    {
      order: 14,
      moduleId: "M05",
      moduleLabel: "Weeks 9–10",
      moduleTitle: "Finish, test and reflect",
      sectionId: "functional-testing",
      sectionTitle: "Functional testing against the design criteria",
      theoryPath: "weeks9-10/index.html#functional-testing",
      outcome: "MATCHED",
      teachingClaim: "Useful product tests reproduce realistic use, control conditions and produce consistent, repeatable evidence.",
      reasonToWatch: "See how professional product testing links realistic use with repeatable conditions and user experience.",
      watchFor: "What makes a test fair enough for another person to repeat and compare?",
      equivalentPath: "Use the adjacent Desk Tidy test table to check storage, access, stability, desk fit and workmanship with intended stationery, then record specific observations and photographs.",
      evidenceLink: "Supports the functional-testing checks and evidence linked directly to the original design criteria.",
      sourceBoundary: "The laboratory examples show testing principles only. Desk Tidy students use the safe, non-destructive tests and intended items named in the adjacent theory, with teacher approval for any adjustment.",
      video: {
        id: "UtKed0o2Q0A",
        title: "Consumer Product Testing - Design and Sustainability (1/7)",
        channel: "OpenLearn from The Open University",
        durationSeconds: 255,
        durationLabel: "4:15",
        segmentStart: 17,
        segmentEnd: 118,
        segmentLabel: "0:17–1:58",
        sampledSegment: "0:17–1:30",
        sampleEvidence: "The official transcript explains consistent, repeatable tests that replicate consumer use, control conditions and include user panels.",
        intelligibility: "PASS — clear documentary narration; the official Open University transcript confirms the sampled content and the live clip supplies English captions.",
        thumbnailUrl: "https://i.ytimg.com/vi/UtKed0o2Q0A/mqdefault.jpg",
        thumbnailWidth: 320,
        thumbnailHeight: 180,
        watchUrl: "https://www.youtube.com/watch?v=UtKed0o2Q0A&t=17s",
        embedUrl: "https://www.youtube-nocookie.com/embed/UtKed0o2Q0A"
      }
    },
    {
      order: 15,
      moduleId: "M05",
      moduleLabel: "Weeks 9–10",
      moduleTitle: "Finish, test and reflect",
      sectionId: "evaluation-reflection",
      sectionTitle: "Evaluation, presentation and reflection",
      theoryPath: "weeks9-10/index.html#evaluation-reflection",
      outcome: "MATCHED",
      teachingClaim: "Evaluation uses test evidence to ask what worked, why it worked or failed, and what realistic improvement follows.",
      reasonToWatch: "Hear a student-friendly explanation of how honest testing leads to evaluation, improvement and further learning.",
      watchFor: "Which questions turn a test result into an evidence-based evaluation and next improvement?",
      equivalentPath: "Use the adjacent criterion → evidence → judgement → improvement → reflection structure, then assemble the student's own drawings, process photographs and test results into a truthful presentation.",
      evidenceLink: "Supports the final evaluation, presentation sequence and reflection on challenge, learning and improvement.",
      sourceBoundary: "The engineering examples are general. The student's own Desk Tidy criteria, evidence and approved decisions must control the evaluation; faults should not be hidden.",
      video: {
        id: "fxJWin195kU",
        title: "The Engineering Process: Crash Course Kids #12.2",
        channel: "Crash Course Kids",
        durationSeconds: 317,
        durationLabel: "5:17",
        segmentStart: 205,
        segmentEnd: 280,
        segmentLabel: "3:25–4:40",
        sampledSegment: "Evaluation and iteration passage, approximately 3:25–4:40",
        sampleEvidence: "Defines evaluation as questioning what worked, why it worked or failed and how it could be improved, then explains returning to earlier design stages.",
        intelligibility: "PASS — lively, student-accessible professional narration with manual English captions; exact wording was checked against the current transcript.",
        thumbnailUrl: "https://i.ytimg.com/vi/fxJWin195kU/maxresdefault.jpg",
        thumbnailWidth: 1280,
        thumbnailHeight: 720,
        watchUrl: "https://www.youtube.com/watch?v=fxJWin195kU&t=205s",
        embedUrl: "https://www.youtube-nocookie.com/embed/fxJWin195kU"
      }
    }
  ]
};
